---

- hosts: localhost

  # clone OMERO ansible project
  tasks:
    - git: repo=https://github.com/hajaalin/omero-ansible.git 
           dest=/opt/omero-ansible
    - shell: cd /opt/omero-ansible; git checkout split_server_roles

